### PR TITLE
Define file by sample

### LINKED ISSUE #53: Define file upload type by sample
It was reported here and there and today I got down to investigate the issue: many people are reporting even though they registered custom file type to be "uploadable" the upload still fails. 

After long investigation I found different tools reports different mime type for the same file. 

I checked some .tar.gz file and it's mime type is:
- in online tool https://www.htmlstrip.com/mime-file-type-checker it is `application/x-gzip`
- in linux command line `xdg-mime query filetype arch.tar.gz` it is `application/x-compressed-tar`
- if I run PHP script which is the same as in WP function `wp_check_file_type_and_ext()` then it is `application/gzip` (the script below)

Users don't know which mime type they should specify when they are defining their rules in the plugin (and it should be the one which WordPress uses, the last, the script I wrote below is code I extracted from WP function to check mime type, see `\wp_check_filetype_and_ext`)

My propositions, two approaches:

### Idea 1: More descriptive "file upload failed" messages

 I propose to modify all "file upload failed" messages to show the reason in case it was mime. Something like "file upload failed, mime `blah/x-blah` is not supported. 

User, when see such info, will go to file upload types configuration and will adjust his definitions to cover such mime.

Drawback: It is probably not possible t modify all error messages as they can come from different places: 
- when user uploads file to standard Media library, WP will print the error
- when user uploads file with WPForms, WPForms rpints the error (side note: user will see it, not site admin so site admin will not be aware there is any issue; we can overcome this problem by adding some error logging)
- any other plugin can have their own logic to handle failed upload

### Idea 2: Add file type tester (or allow to define file upload type by sample file)

Now the site admin defines allowed custom files by manually typing the extension and mime type. My idea is to add below that form some row with label "Define allowed file type by uploading sample file" and button to upload file. When site admin uploads file, we could define fetch its extension and mime type (with the script at the bottom of this post) and automatically fill extension and mime type in the form which we already have)

Bear in mind, we don't need to save that file anywhere, script which will be processing the file will just check extension and mime and do not proceed. So it is safe (I am not 100% sure of that)

Drawback: Actually none (except security concerns). It will need some coding, some UI design work but _we always do the right things_ 

p.s. **just a hint: we can apply both ideas at the same time ;)**

-----------------
checktype.php:
```
<?php
$finfo     = finfo_open( FILEINFO_MIME_TYPE );
$real_mime = finfo_file( $finfo, $argv[1] );
finfo_close( $finfo );

echo $real_mime . PHP_EOL;
```

How to use this script:
1. place the file `checktype.php` on your server
2. add execution chmod for the file `chmod +x checktype`
3. place in the same directory the file you want to check mime (for example `font.otf`)
4. run in console `./checktype.php font.otf`

### PR DESCRIPTION
**Pull request by kkarpieszuk**
Steps: 
1. go to wp-admin > settings > file upload types
2. see at the bottom dropzone to choose file 
3. click on it or drag some file
4. make sure below this you can see a new row with file data
5. make sure you can add another file the same way
6. make sure you can add another file by clicking (+) icon in a row
7. save settings
8. create wpforms form with upload file field and test if you can upload files  you just defined to be uploadable
9. test the rest of the FUT functionality

Fixes #53 

image

### CODE REVIEW

File: src/Settings.php [hunk 1]
```diff
@@ -680,4 +703,36 @@ public function remove_notices() { // phpcs:ignore Generic.Metrics.NestingLevel.
 			}
 		}
 	}
+
+	/**
+	 * Check the sample file.
+	 *
+	 * @since 1.4.0
```
Comment (kkarpieszuk) [inline src/Settings.php:728]: I don't remember whether I should hardcode the version number or use {VERSION}, how can we check?

File: src/Settings.php [hunk 2]
```diff
@@ -78,6 +79,14 @@ public function enqueue_assets() {
 			FILE_UPLOAD_TYPES_VERSION
 		);
 
+		wp_enqueue_script(
+			'file-upload-types-dropzone',
+			plugins_url( 'assets/js/dropzone.min.js', FILE_UPLOAD_TYPES_PLUGIN_FILE ),
+			[],
+			FILE_UPLOAD_TYPES_VERSION,
```
Comment (wppunk) [inline src/Settings.php]: Let's use the actual Dropzone library version. Have you used `5.9.3` or `6.0.0-beta2`?

File: src/Settings.php [hunk 3]
```diff
@@ -680,4 +703,36 @@ public function remove_notices() { // phpcs:ignore Generic.Metrics.NestingLevel.
...
+	 * Check the sample file.
+	 *
+	 * @since 1.4.0
+	 */
+	public function check_sample() {
+
+		// verify file_upload_types_nonce nonce.
+		check_ajax_referer( 'file_upload_types_nonce', 'nonce' );
+
+		// @todo: add nonce verification.
```
Comment (wppunk) [inline src/Settings.php]: We can remove the `todo`

File: assets/js/script.js [hunk 4]
```diff
@@ -1,12 +1,15 @@
-/* global file_upload_types_params, jQuery */
+/* global file_upload_types_params, jQuery, Dropzone */
 
 'use strict';
 
+Dropzone.autoDiscover = false;
```
Comment (wppunk) [inline assets/js/script.js:5]: It was dropped in v6.0. Do we really need it?

File: src/Settings.php [hunk 5]
```diff
@@ -680,4 +703,36 @@ public function remove_notices() { // phpcs:ignore Generic.Metrics.NestingLevel.
...
+		if ( isset( $_FILES['file'] ) ) {
+			$sample         = $_FILES['file'];
+			$sample['name'] = preg_replace( '/[^a-zA-Z0-9\._-]/', '', $sample['name'] );
+			$sample['name'] = uniqid() . '_' . $sample['name'];
+
+			$finfo     = finfo_open( FILEINFO_MIME_TYPE );
+			$mime_type = finfo_file( $finfo, $sample['tmp_name'] );
+			$extension = pathinfo( $sample['name'], PATHINFO_EXTENSION );
+
+			finfo_close( $finfo );
```
Comment (wppunk) [inline src/Settings.php]: ### Extension.

1. The regex we can replace with the `sanitize_file_name` function. No regex no problem.
2. I didn't get why we need `uniqid` here. If we really need it, please add a comment since it's not obvious.

### Mime type

I read all the threads in issue and Slack and got the mime-type hell.

But according to PHP documentation, we can replace `finfo...` functions with `mime_content_type`. It looks like under the hood it's the same, but it's much easier to read.

File: assets/js/script.js [hunk 6]
```diff
@@ -46,14 +49,62 @@ jQuery( function ( $ ) {
...
+		.on( 'click', '#c_types_file_sample_button a', function ( e ) {
+			e.preventDefault();
+
+			$( '.repetitive-fields' ).show();
 		} );
+
+	let uploaded = 0;
+
+	let SampleFileDropzone = new Dropzone( '#c_types_file_sample_button', {
+		url: ajaxurl,
```
Comment (wppunk) [inline assets/js/script.js:77]: We can add the `ajaxurl` in the `global` comment on the 1st line of the file
or 
We can add the `ajaxurl` to our `file_upload_types_params` variable.

File: assets/js/script.js [hunk 7]
```diff
@@ -46,14 +49,62 @@ jQuery( function ( $ ) {
...
+		allowMultiple: false,
+		previewTemplate: '<div style="display:none"></div>',
+		init: function() {
+			this.on( 'sending', function( file, xhr, formData ) {
+				formData.append( 'action', 'file_upload_types_check_sample' );
+				formData.append( 'nonce', file_upload_types_params.nonce );
+
+				$( '.file-upload-types-dropzone span.icon' ).addClass( 'loading' );
+			} );
+			this.on( 'success', function( file, response ) {
```
Comment (wppunk) [inline assets/js/script.js:88]: What do you think if we cover an edge case when we can't detect mime type or extension?

I would return the 400th error and add the `on( 'error', ...` callback which shows an error message for customers.

**Review by wppunk — CHANGES_REQUESTED** [review]
@kkarpieszuk nice work Konrad 👍 You made a really deep research and solution looks pretty solid. Keep it up.

However, I noticed a few things which we can improve in your solution.

Firstly, I caught a weird bug. I uploaded the same file a few times and after 3rd time I start noticed an empty rows, here is the screencast:

https://github.com/awesomemotive/file-upload-types/assets/19273242/378c7055-ac4a-4c13-8348-fce8acafdb28

File: src/Settings.php (hunk 5 above)
Comment (kkarpieszuk) [reply src/Settings.php]: Thanks for the suggestions 1. and 2. I changed that (about uniqid, I frankly don't remember why I used  this, I wrote some parts of this code 1,5 year ago, now I removed it). 

About `finfo` I will leave it as is. I want to have this code checking the type the same way as build in Wordpress function `wp_check_filetype_and_ext` does because we need to have the same results when user start uploading real files. For now both `finfo` and `mime_content_type` seems to work the same. But I prefer to use the same WP is using

File: assets/js/script.js (hunk 6 above)
Comment (kkarpieszuk) [reply assets/js/script.js:77]: done the first one

File: assets/js/script.js (hunk 4 above)
Comment (kkarpieszuk) [reply assets/js/script.js:5]: you are right, with 6.0 it is not needed

File: src/Settings.php (hunk 2 above)
Comment (kkarpieszuk) [reply src/Settings.php]: I simply copied the one from WPForms core without checking the version. Now updated but to `6.0.0-beta1`, where did you find `6.0.0-beta2`?

File: assets/js/script.js (hunk 7 above)
Comment (kkarpieszuk) [reply assets/js/script.js:88]: done

**Comment by kkarpieszuk** [comment]
@wppunk please continue the review. I applied all your suggestions or commented them. I also fixed the error you found

File: src/Settings.php (hunk 2 above)
Comment (kkarpieszuk) [reply src/Settings.php]: nevermind, I found beta 2 :)

**Comment by kkarpieszuk** [comment]
I did the extended testing as @joannafoss asked (as this will not be tested by QA team most likely). 

The proposed interface for uploading files works with no issues (I found some minor issues and fixed them).

While testing this I found other issues in not related areas, they should be handled separately. They are:

- if you define more than one mime type for the extension, only the first one is in use in some cases. This is serious issue which still will be blocking some users from getting file uploads working but the fix is not trivial and should be addressed in a next release (it is broken functionality in one of main functions in the plugin if not in the most important one, the risk is very high). I created separate ticket for this #77 

- there is problem inside WPForms plugin (so not in FUT) where even if you define .js, .html files as uploadable, WPForms has custom rules to block them. I escalated it to WPForms project https://github.com/awesomemotive/wpforms-plugin/issues/11220

@wppunk this is ready for the final testing from you.

**Review by wppunk — APPROVED** [review]
@kkarpieszuk thanks for your changes. LGTM 👍

File: src/Settings.php (hunk 1 above)
Comment (kagg-design) [reply src/Settings.php:728]: @kkarpieszuk npm run gulp build

**Review by kagg-design — APPROVED** [review]
Thank you, @kkarpieszuk, good work!
